### ISSUE TITLE
How to detect zg or uni?

### ISSUE THREAD

**Issue by HtetLinThu** [tintnaingwinn/MyanFont#6]
How to detect zg or uni?
I have the error.

Call to undefined method Tintnaingwin\MyanFont\MyanFont::isZgOrUni()

isZgOrUni method is not working.

**Comment by tintnaingwinn** [comment]
Hello @HtetLinThu ,

You can use with Facade.
`use MyanFont;`

I recommended use dev-master version `composer require tintnaingwin/myanfont:dev-master`

Dev-master can use helper ( `isZgOrUni()` )
